### PR TITLE
Support ghc-exactprint-0.6.3

### LINKED ISSUE #53: Compilation error
On CI https://travis-ci.org/github/ndmitchell/hlint/jobs/667865822 I'm getting:

```
Building executable 'refactor' for apply-refact-0.6.0.0..
[1 of 6] Compiling Paths_apply_refact ( dist/build/refactor/autogen/Paths_apply_refact.hs, dist/build/refactor/refactor-tmp/Paths_apply_refact.o )
[2 of 6] Compiling Refact.Utils     ( src/Refact/Utils.hs, dist/build/refactor/refactor-tmp/Refact/Utils.o )
[3 of 6] Compiling Refact.Fixity    ( src/Refact/Fixity.hs, dist/build/refactor/refactor-tmp/Refact/Fixity.o )
src/Refact/Fixity.hs:59:27: error:
    Ambiguous occurrence ‘noExt’
    It could refer to either ‘HsExtension.noExt’,
                             imported from ‘HsExtension’ at src/Refact/Fixity.hs:12:1-18
                          or ‘Language.Haskell.GHC.ExactPrint.Types.noExt’,
                             imported from ‘Language.Haskell.GHC.ExactPrint.Types’ at src/Refact/Fixity.hs:16:1-73
   |
59 |   = return $ L loc (OpApp noExt e1 op2 e2)
   |                           ^^^^^
```

Is the issue a change to ghc-exactprint-0.6.3?

### PR DESCRIPTION
**Pull request by ndmitchell**
Fixes #53

### CODE REVIEW

**Comment by ndmitchell** [comment]
Any idea what it would take to merge and release this code? We are planning to release HLint 3.0 once we have a working ghc-exactprint support.

**Comment by mpickering** [comment]
Why does this block the hlint release? Hlint doesn't depend on this library?

**Comment by ndmitchell** [comment]
There's no library dependency, but we use apply-refact in the test suite of HLint (to ensure the tests are working), and quite a lot of people use HLint and apply-refact together, so making a release of only HLint will cause lots of bits not to work for people. Therefore we do our best to release when everything is happy.

If however it's going to be a while before apply-refact is working with GHC 8.10 and latest versions of dependencies then we'll release but add a warning that the refactoring bits are broken.

**Comment by mpickering** [comment]
I am unfortunately suffering some issues with my wrists and so can't commit to working on this in the near future. There are a few other people with upload rights I think.

**Comment by GeorgeCo** [comment]
@ndmitchell 
If this doesn't get picked up soon I think it would be good to move forward on HLint 3.0 without this for now

**Comment by mpickering** [comment]
Fixed my wrists and uploaded a version which supports 8.10.

**Comment by ndmitchell** [comment]
Thanks a lot! I enabled it and it works perfectly with HLint, so we'll make a release in the near future.
