### ISSUE TITLE
Failed to build 0.7.0.0 due to ghc-exactprint-0.6.3 

### ISSUE THREAD

**Issue by jneira** [mpickering/apply-refact#74]
* `0.7`is needed to build with ghc < 8.10
* There is no upper bound over ghc-exactprint
* `cabal build hls-ghc-lib -w ghc-8.8.3`:
```
[1 of 3] Compiling Refact.Utils     ( src\Refact\Utils.hs, dist\build\Refact\Utils.o )
[2 of 3] Compiling Refact.Fixity    ( src\Refact\Fixity.hs, dist\build\Refact\Fixity.o )

src\Refact\Fixity.hs:59:27: error:
    Ambiguous occurrence ‘noExt’
    It could refer to
       either ‘HsExtension.noExt’,
              imported from ‘HsExtension’ at src\Refact\Fixity.hs:12:1-18
           or ‘Language.Haskell.GHC.ExactPrint.Types.noExt’,
              imported from ‘Language.Haskell.GHC.ExactPrint.Types’ at src\Refact\Fixity.hs:16:1-73
   |
59 |   = return $ L loc (OpApp noExt e1 op2 e2)
   |                           ^^^^^

src\Refact\Fixity.hs:74:26: error:
    Ambiguous occurrence ‘noExt’
    It could refer to
       either ‘HsExtension.noExt’,
              imported from ‘HsExtension’ at src\Refact\Fixity.hs:12:1-18
           or ‘Language.Haskell.GHC.ExactPrint.Types.noExt’,
              imported from ‘Language.Haskell.GHC.ExactPrint.Types’ at src\Refact\Fixity.hs:16:1-73
   |
74 |   = return (L loc (OpApp noExt e1 op2 e2))
   |                          ^^^^^

src\Refact\Fixity.hs:80:31: error:
    Ambiguous occurrence ‘noExt’
    It could refer to
       either ‘HsExtension.noExt’,
              imported from ‘HsExtension’ at src\Refact\Fixity.hs:12:1-18
           or ‘Language.Haskell.GHC.ExactPrint.Types.noExt’,
              imported from ‘Language.Haskell.GHC.ExactPrint.Types’ at src\Refact\Fixity.hs:16:1-73
   |
80 |       let res = L loc (NegApp noExt new_e neg_name)
   |                               ^^^^^

src\Refact\Fixity.hs:96:27: error:
    Ambiguous occurrence ‘noExt’
    It could refer to
       either ‘HsExtension.noExt’,
              imported from ‘HsExtension’ at src\Refact\Fixity.hs:12:1-18
           or ‘Language.Haskell.GHC.ExactPrint.Types.noExt’,
              imported from ‘Language.Haskell.GHC.ExactPrint.Types’ at src\Refact\Fixity.hs:16:1-73
   |
96 |   = return $ L loc (OpApp noExt e1 op1 e2)
   |                           ^^^^^

src\Refact\Fixity.hs:103:27: error:
    Ambiguous occurrence ‘noExt’
    It could refer to
       either ‘HsExtension.noExt’,
              imported from ‘HsExtension’ at src\Refact\Fixity.hs:12:1-18
           or ‘Language.Haskell.GHC.ExactPrint.Types.noExt’,
              imported from ‘Language.Haskell.GHC.ExactPrint.Types’ at src\Refact\Fixity.hs:16:1-73
    |
103 |   = return $ L loc (OpApp noExt e1 op e2)
    |                           ^^^^^
cabal.exe: Failed to build apply-refact-0.7.0.0 (which is required by
lib:hls-ghc-lib from haskell-language-server-0.1.0.0). See the build log above
for details.
```
* `cabal build hls-ghc-lib -w ghc-8.8.3 --constraint="ghc-exactprint == 0.6.2"` builds it succesfully
* Maybe adding a cabal revision with the upper bound would fix the issue

**Comment by zliu41** [comment]
Thanks for reporting the problem. Version 0.8.1.0 is ready to be released (#72) which will support GHC 8.6, 8.8 and 8.10. I don't yet have Hackage permission for this package. @mpickering @fendor do you mind adding me to the maintainer group?

**Comment by zliu41** [comment]
Published 0.8.1.0 and 0.7.0.0 r1.

**Comment by jneira** [comment]
@zliu41 great work! will the `0.7.0.0 r1' release be published in hackage as a new minor version or a hackage revision?

**Comment by zliu41** [comment]
@jneira Thanks. It's a metadata revision.
