### ISSUE TITLE
Build failure on GHC 9.4

### ISSUE THREAD

**Issue by milloni** [mpickering/apply-refact#127]
Hi, just wondering if anyone's working on a GHC 9.4 port? Cc: @zliu41 @alanz

**Comment by alanz** [comment]
I just published ghc-exactprint1.6, which supports GHC 9.4.1 and 9.4.2

**Comment by July541** [comment]
I have a rough [branch](https://github.com/July541/apply-refact/tree/ghc-9.4) working on this, tests look fine.

https://github.com/July541/apply-refact/actions/runs/3259599078

**Comment by juhp** [comment]
Disabling for ghc-9.4 Stackage Nightly:
```
Building test suite 'test' for apply-refact-0.10.0.0..                                                                              
[2 of 9] Compiling Refact.Compat                                  

/var/stackage/work/unpack-dir/unpacked/apply-refact-0.10.0.0-4a0dca717dcd79ebca2f66523ba9b8be29e71ab7004f3d4b3b36b7d8b0d195aa/src/Re
fact/Compat.hs:183:15: error:
    Not in scope: type constructor or class ‘ErrorMessages’                                                                         
    |                                                             
183 | type Errors = ErrorMessages                                 
    |               ^^^^^^^^^^^^^         
```

**Comment by andreasabel** [comment]
Isn't this issue stale?  In case, please close.

**Comment by zliu41** [comment]
Thanks @andreasabel
